# Generated by Django 4.2.2 on 2023-06-17 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de Categoria')),
                ('nombreCategoria', models.CharField(blank=True, max_length=50, verbose_name='Nombre de Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id Producto')),
                ('marca', models.CharField(max_length=30, verbose_name='Marca del Producto')),
                ('precioProducto', models.IntegerField(verbose_name='Precio Producto')),
                ('stock', models.IntegerField(verbose_name='Cantidad en Stock')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda_mascotas.categoria', verbose_name='Categoria')),
            ],
        ),
    ]
